### ISSUE TITLE
gpiod_chip_open requires access to all gpio chips

### ISSUE THREAD

**Issue by mvargasevans** [hhk7734/python3-gpiod#19]
Hi,
First, thanks for writing this library.

During opening a chip with gpiod.chip("chip"), it happened to me that in my system an access denied took place.
The reason is that I have 2 gpiochips, and only one of them is on the group with access control.

While looking at the open function, I believe that this has to do with open calling gpioinfo which requires access to all gpiochips.
I can correct this in my system, but I wanted to ask if this is unavoidable, since it would be great that a usage of a gpiochip does not depend on the status of the other gpiochips.

Thanks

**Comment by hhk7734** [comment]
I cannot understand your situation.
